name: flutter_html_2
description: A Flutter widget for rendering static HTML and CSS as Flutter widgets.
version: 0.0.9
homepage: https://github.com/hamzasidd3634/flutter_html

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.2.0'

dependencies:
  # Plugin for parsing html
  html: ^0.15.4

  # Plugin for parsing css
  csslib: ^1.0.0

  # Plugin for firstWhereOrNull extension on lists
  collection: ^1.18.0

  # plugin to manage lists and counting in a variety of styles
  list_counter: ^1.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  meta: ^1.15.0
  melos: ^6.1.0
dependency_overrides:

  meta: ^1.15.0

screenshots:
  - description: 'An example of the output produced by flutter_html_2'
    path: example/screenshots/flutter_html_screenshot.png
  - description: 'Continued example of the output produced by flutter_html_2'
    path: example/screenshots/flutter_html_screenshot1.png
  - description: 'Continued example of the output produced by flutter_html_2'
    path: example/screenshots/flutter_html_screenshot2.png
  - description: 'Continued example of the output produced by flutter_html_2'
    path: example/screenshots/flutter_html_screenshot3.png
  - description: 'Another example of the output produced by flutter_html_2'
    path: example/screenshots/flutter_html_readme_screenshot.png

funding:
  - https://opencollective.com/flutter_html

#topics:
#  - html
#  - css
#  - widgets
#  - layout
#  - flutter_html
