name: flutter_html_all_2
description: All optional flutter_html widgets, bundled into a single package.
version: 0.0.3
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html_2: ^0.0.3
  flutter_html_audio_2: ^0.0.3
  flutter_html_iframe_2: ^0.0.3
  flutter_html_math_2: ^0.0.3
  flutter_html_svg_2: ^0.0.3
  flutter_html_table_2: ^0.0.3
  flutter_html_video_2: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - widgets
  - layout
  - flutter_html
