name: flutter_html_svg_2
description: This extension package allows the <svg> tag and svg-based img sources to be rendered using the flutter_html package
version: 0.0.3
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html_2: ^0.0.3
  flutter_svg: '>=1.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  meta: ^1.12.0

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - svg
  - images
  - flutter_html
